#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-scales
Version  : 1.4.0
Release  : 107
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/scales_1.4.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/scales_1.4.0.tar.gz
Summary  : Scale Functions for Visualization
Group    : Development/Tools
License  : MIT
Requires: R-R6
Requires: R-RColorBrewer
Requires: R-cli
Requires: R-farver
Requires: R-glue
Requires: R-labeling
Requires: R-lifecycle
Requires: R-rlang
Requires: R-viridisLite
BuildRequires : R-R6
BuildRequires : R-RColorBrewer
BuildRequires : R-cli
BuildRequires : R-farver
BuildRequires : R-glue
BuildRequires : R-hms
BuildRequires : R-labeling
BuildRequires : R-lifecycle
BuildRequires : R-rlang
BuildRequires : R-viridisLite
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
for automatically determining breaks and labels for axes and legends.

%prep
%setup -q -n scales
pushd ..
cp -a scales buildavx2
popd
pushd ..
cp -a scales buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1745599229

%install
export SOURCE_DATE_EPOCH=1745599229
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/scales/DESCRIPTION
/usr/lib64/R/library/scales/INDEX
/usr/lib64/R/library/scales/LICENSE
/usr/lib64/R/library/scales/Meta/Rd.rds
/usr/lib64/R/library/scales/Meta/features.rds
/usr/lib64/R/library/scales/Meta/hsearch.rds
/usr/lib64/R/library/scales/Meta/links.rds
/usr/lib64/R/library/scales/Meta/nsInfo.rds
/usr/lib64/R/library/scales/Meta/package.rds
/usr/lib64/R/library/scales/NAMESPACE
/usr/lib64/R/library/scales/NEWS.md
/usr/lib64/R/library/scales/R/scales
/usr/lib64/R/library/scales/R/scales.rdb
/usr/lib64/R/library/scales/R/scales.rdx
/usr/lib64/R/library/scales/help/AnIndex
/usr/lib64/R/library/scales/help/aliases.rds
/usr/lib64/R/library/scales/help/figures/README-labels-1.png
/usr/lib64/R/library/scales/help/figures/README-labels-2.png
/usr/lib64/R/library/scales/help/figures/README-palettes-1.png
/usr/lib64/R/library/scales/help/figures/README-transforms-1.png
/usr/lib64/R/library/scales/help/figures/README-unnamed-chunk-3-1.png
/usr/lib64/R/library/scales/help/figures/README-unnamed-chunk-4-1.png
/usr/lib64/R/library/scales/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/scales/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/scales/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/scales/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/scales/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/scales/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/scales/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/scales/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/scales/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/scales/help/figures/logo.png
/usr/lib64/R/library/scales/help/figures/logo.svg
/usr/lib64/R/library/scales/help/paths.rds
/usr/lib64/R/library/scales/help/scales.rdb
/usr/lib64/R/library/scales/help/scales.rdx
/usr/lib64/R/library/scales/html/00Index.html
/usr/lib64/R/library/scales/html/R.css
/usr/lib64/R/library/scales/tests/testthat.R
/usr/lib64/R/library/scales/tests/testthat/_snaps/breaks-log.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/colour-mapping.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/label-bytes.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/label-date.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/label-number-auto.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/label-number.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/label-ordinal.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/pal-manual.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/palette-registry.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/scale-continuous.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/trans-compose.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/trans-date.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/trans-numeric.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/trans.md
/usr/lib64/R/library/scales/tests/testthat/_snaps/utils.md
/usr/lib64/R/library/scales/tests/testthat/test-bounds.R
/usr/lib64/R/library/scales/tests/testthat/test-breaks-log.R
/usr/lib64/R/library/scales/tests/testthat/test-breaks.R
/usr/lib64/R/library/scales/tests/testthat/test-colour-manip.R
/usr/lib64/R/library/scales/tests/testthat/test-colour-mapping.R
/usr/lib64/R/library/scales/tests/testthat/test-colour-ramp.R
/usr/lib64/R/library/scales/tests/testthat/test-full-seq.R
/usr/lib64/R/library/scales/tests/testthat/test-label-bytes.R
/usr/lib64/R/library/scales/tests/testthat/test-label-compose.R
/usr/lib64/R/library/scales/tests/testthat/test-label-currency.R
/usr/lib64/R/library/scales/tests/testthat/test-label-date.R
/usr/lib64/R/library/scales/tests/testthat/test-label-dictionary.R
/usr/lib64/R/library/scales/tests/testthat/test-label-expression.R
/usr/lib64/R/library/scales/tests/testthat/test-label-glue.R
/usr/lib64/R/library/scales/tests/testthat/test-label-log.R
/usr/lib64/R/library/scales/tests/testthat/test-label-number-auto.R
/usr/lib64/R/library/scales/tests/testthat/test-label-number-si.R
/usr/lib64/R/library/scales/tests/testthat/test-label-number.R
/usr/lib64/R/library/scales/tests/testthat/test-label-ordinal.R
/usr/lib64/R/library/scales/tests/testthat/test-label-percent.R
/usr/lib64/R/library/scales/tests/testthat/test-label-pvalue.R
/usr/lib64/R/library/scales/tests/testthat/test-label-scientific.R
/usr/lib64/R/library/scales/tests/testthat/test-label-wrap.R
/usr/lib64/R/library/scales/tests/testthat/test-labels-retired.R
/usr/lib64/R/library/scales/tests/testthat/test-minor_breaks.R
/usr/lib64/R/library/scales/tests/testthat/test-offset-by.R
/usr/lib64/R/library/scales/tests/testthat/test-pal-.R
/usr/lib64/R/library/scales/tests/testthat/test-pal-hue.R
/usr/lib64/R/library/scales/tests/testthat/test-pal-manual.R
/usr/lib64/R/library/scales/tests/testthat/test-palette-registry.R
/usr/lib64/R/library/scales/tests/testthat/test-range.R
/usr/lib64/R/library/scales/tests/testthat/test-round-any.R
/usr/lib64/R/library/scales/tests/testthat/test-scale-continuous.R
/usr/lib64/R/library/scales/tests/testthat/test-scale-discrete.R
/usr/lib64/R/library/scales/tests/testthat/test-trans-compose.R
/usr/lib64/R/library/scales/tests/testthat/test-trans-date.R
/usr/lib64/R/library/scales/tests/testthat/test-trans-numeric.R
/usr/lib64/R/library/scales/tests/testthat/test-trans.R
/usr/lib64/R/library/scales/tests/testthat/test-utils.R
